### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by mbenitog** [BRA1L0R/hopper-rs#10]
Hi! Could you look into making this compatible with Bedrock/Geyser?
It could be a very interesting alternative for Bedrock proxies as Nginx does not quite work well with Geyser and there is not much else out there.

**Comment by BRA1L0R** [comment]
Hi @mbenitog, thank you for your suggestion.

However, the bedrock protocol does not include any information regarding what server it is connecting to, furthermore, it would go out of this proxy's scope. 

I might create something similar to this project for Bedrock in the future though.
