### ISSUE TITLE
Suggestion: Reload config for High Availability

### ISSUE THREAD

**Issue by Alex1607** [BRA1L0R/hopper-rs#16]
Maybe it would be possible to add a reload mechanism into hopper to allow for easy changes without having to disconnect all users.
Like for example, if I want to add a new route, hopper would kick all users because I have to restart it.
Furthermore, this is something which might be important for me but not for others.
But I would love the ability to change the IP of the backend server, reload hopper, and then have only new users connect to this new IP while users that are currently connected keep their current connection.

**Comment by BRA1L0R** [comment]
It could be done with a `SIGHUP` process signal, just like nginx. Did you think specifically of a way to do such thing without process signals?

**Comment by Alex1607** [comment]
My first Idea was to just add a command that can be run in the application itself. Like a `reload` or `help` command.
But I suppose it doesn't matter how exactly something like this is implemented, the advantage of a command system, of course, would be that it would allow for other features via commands in the future.

**Comment by BRA1L0R** [comment]
Hm, adding a whole command system would be both a challenge and kind of out of scope of the project.

Adding reload via SIGHUB would allow systemd users to just run `systemctl reload hopper` for example, and there sure gotta be an equivalent for docker.

**Comment by Alex1607** [comment]
Sure that also sound like a good way
