### ISSUE TITLE
Ping seems quite volatile

### ISSUE THREAD

**Issue by Alex1607** [BRA1L0R/hopper-rs#18]
Hey,

I replaced HAProxy with Hopper as a proxy and noted the following:
With HAProxy, my ping appears to be stable at around ~20:
![image](https://user-images.githubusercontent.com/19777054/213786526-cece4746-0dea-40d4-8750-53dc939954ce.png)

With Hopper, it likes to jump around quite a lot and is way higher than it was:
![image](https://user-images.githubusercontent.com/19777054/213786592-a26d3a26-7c3c-4af2-8758-3d3e3e656881.png)

(This behavior is also seen by different users from different parts of the country with different ISPs)

Both Revers Proxies connect to the same Minecraft Proxy and are hosted by the same Hoster. And both Revers Proxies are using the Proxy Protocol.
I can give you both Revers Proxies IPs in case you are interested and want to investigate that.

**Comment by BRA1L0R** [comment]
Hi, does this happen when there are multiple players connected on the same proxy or does it happen with only a player connected too?

**Comment by Alex1607** [comment]
> Hi, does this happen when there are multiple players connected on the same proxy or does it happen with only a player connected too?

Happens in both cases, with just me and with dozens of players connected

**Comment by BRA1L0R** [comment]
I just released a commit with what I think might be the solution to the problem. If not then I will continue to investigate.

**Comment by Alex1607** [comment]
It definitely improved the volatile part. It no longer jumps around every 2 to 3 seconds, especially not up to +100, however it is still consistently around 1.5x to 2x higher than with HAProxy.

**Comment by BRA1L0R** [comment]
Basically, HAProxy uses [splice](https://man7.org/linux/man-pages/man2/splice.2.html) on linux to zero-copy transfer data from the client socket to the server socket.

The only problem is that splicing between sockets requires the creation of a pipe. So a total of 2 pipes per connection, and creating pipes is an "expensive" operation. HAProxy solves this by having a pipe pool, which is probably what I will implement in hopper too.

**Comment by faultydev** [comment]
Hi there!
Is there an ETA on the new method? :)

**Comment by BRA1L0R** [comment]
@faultydev @Alex1607 sorry for my absence. The fix was just to disable the Nagle algorithm by setting nodelay to true on the sockets.

Rolling out this fix in a few minutes
