### ISSUE TITLE
Root domain

### ISSUE THREAD

**Issue by zGumeloBr** [BRA1L0R/hopper-rs#19]
Good evening, the application is wonderful but I found a small problem, root domains do not work, only suboominios, example the domain test.play.com works but point only the play.com does not work

**Comment by ImFound** [comment]
Hello, can you please send your .toml config?

**Comment by BRA1L0R** [comment]
> Good evening, the application is wonderful but I found a small problem, root domains do not work, only suboominios, example the domain test.play.com works but point only the play.com does not work

As @ImFound said, would you be so kind to provide your connfiguration file?

Thanks

**Comment by zGumeloBr** [comment]
Yes, of course

`listen = "0.0.0.0:25565"

[routing.routes]

"play.kaisenmc.com" = { ip-forwarding = "proxy_protocol", ip = "private-ip:25565" }
"elyzium.me" = { ip-forwarding = "proxy-protocol", ip = "private-ip:25565" }`

elyzium.me does not work

**Comment by ImFound** [comment]
Hello,
on elyzium.me the dns resolution tells me this: "DNS request failed: The domain name referenced in the query does not exist."

The problem is by your side, I think on the DNS management. Good luck ;)

**Comment by zGumeloBr** [comment]
I disabled the DNS to secure my IP

**Comment by zGumeloBr** [comment]
I enabled the route again

**Comment by ImFound** [comment]
it seems to be working...



https://mcsrvstat.us/server/elyzium.me

**Comment by zGumeloBr** [comment]
I finded the problem, thanks :)
