### ISSUE TITLE
Cant connect to server MOTD Error.

### ISSUE THREAD

**Issue by NoahFinleyWolf** [BRA1L0R/hopper-rs#5]
Hi, when I try to connect to the server comes (described above) the error. The funny thing is that when I click on the server I can connect to the server. So no MOTD is displayed. Can you please fix that one also sees a MOTD. THANKS! 
![Screenshot (236)](https://user-images.githubusercontent.com/81982356/183484033-2baaabf9-ac55-489d-a94d-0f5fa29030a6.png)

**Comment by BRA1L0R** [comment]
Hi @NoahFinleyWolf, thank you for showing interest in the project

Would you be so kind to share your config file? Thanks

**Comment by NoahFinleyWolf** [comment]
# the address hopper will listen on
listen = "0.0.0.0:25565"

# general routing configuration
[routing]
default = { ip = "hidden:22342" } # optional
# default = { ip = ["127.0.0.1:12001", "127.0.0.1:12002"] } # load balanced

# list of servers fronted by hopper
[routing.routes]
# simple reverse proxy
"hidden" = { ip = "hidden:22342" } # hostnames are supported too!

**Comment by NoahFinleyWolf** [comment]
And? @BRA1L0R

**Comment by BRA1L0R** [comment]
> And?

I have just returned from a 2 weeks absence, will start investigating on the issue now

**Comment by BRA1L0R** [comment]
@NoahFinleyWolf I will need more information in order to recreate the issue.

1) What minecraft server version are you running behind hopper?
2) Where is hopper being hosted?
2.1 Please include any firewall configuration if you think it may be of interest to this issue
3) Any other details that might be relevant to the investigation...

**Comment by BRA1L0R** [comment]
Closing this issue as it has been probably resolved in the recent wave of bug fixes.
