### ISSUE TITLE
Luckperms "module"

### ISSUE THREAD

**Issue by spannerman79** [BRA1L0R/hopper-rs#6]
I don't think I need to state just how popular and useful Luckperms is as a permission manager.

One of the things that I can do with Luckperms on both Bungee and Server is to allow/deny usergroups connecting to a a host amongst other options.

**Comment by BRA1L0R** [comment]
Hi @spannerman79, thank you for showing interest in the project. In-game commands are not supported at the moment but it is being both researched and worked on.

Hopper as of now does not understand in-game communication such as chat messages (in this case commands) or anything having to do with game mechanics, but this is where I want hopper's future to head to.

**Comment by spannerman79** [comment]
Why was this closed with the `wontfix` label?
