### ISSUE TITLE
CPU max usage

### ISSUE THREAD

**Issue by InfiniteCod3** [BRA1L0R/hopper-rs#7]
Hello, I have set up hopper to proxy a basic spigot server. even when no one uses the proxy, hopper tends to spike the cpu at 100% for like 10 minutes.
![unknown (3)](https://user-images.githubusercontent.com/91837651/186000630-11771b38-bdc4-41d7-b550-3d6fe68fce1a.png)
![unknown (4)](https://user-images.githubusercontent.com/91837651/186000636-23dd5335-b56b-4a7e-ba9a-86c4059009e7.png)

**Comment by BRA1L0R** [comment]
Hi. Thank you for showing interest in the project. This is a potential issue I am aware of and I'd like to investigate further with you. 
- Can you please enable debug logging by running hopper with `RUST_LOG="debug" ./hopper`?

- Also, can you share your config file here?

Thank you very much

**Comment by InfiniteCod3** [comment]
here is my config
[Config.zip](https://github.com/BRA1L0R/hopper-rs/files/9397064/Config.zip)
and i will turn on the debugging and see if there is anything unexpected going on

**Comment by InfiniteCod3** [comment]
It's just weird 1 person joined cpu spiked to 50% second person joined cpu spiked to 100% and there are no errors or any unexpected output.

**Comment by InfiniteCod3** [comment]
Ubuntu 20.04.4 LTS, I'm running the program as root in the root directory with ./hopper or RUST_LOG="debug" ./hopper for the debug

**Comment by BRA1L0R** [comment]
Also, your config file is wrong. It shouldn't be the cause of the problem but you might want to try with a correct configuration file:

```
listen = "0.0.0.0:25565"

[routing.routes]
"katana.lol" = { ip-forwarding = "bungeecord", ip = "178.63.42.237:20006" }
```

**Comment by InfiniteCod3** [comment]
oh yeah thanks, i doubt its gonna fix the issue tho

**Comment by LegendaryOfCats** [comment]
💀

**Comment by BRA1L0R** [comment]
> i doubt its gonna fix the issue tho

yea i know, can you try running it without bungeecord ip forwarding? thanks

**Comment by InfiniteCod3** [comment]
> > i doubt its gonna fix the issue tho
> 
> yea i know, can you try running it without bungeecord ip forwarding? thanks

stills does the same, the cpu still spikes up

**Comment by BRA1L0R** [comment]
> stills does the same, the cpu still spikes up

The issue may be the low core count which creates some sort of spinlock condition between tasks. I will try doing some local testing with a limited number of cores

**Comment by BRA1L0R** [comment]
![image](https://user-images.githubusercontent.com/17928339/186017100-b7570b4b-4adb-4bd4-b045-f55e08f64081.png)
I was indeed able to recreate the issue with a low core count. Yikes.

**Comment by BRA1L0R** [comment]
I have just checked. Any core count ties hopper in an infinite loop. This appears to be a problem with the latest version.

**Comment by BRA1L0R** [comment]
Hi. I think i have identified and solved this issue. Can you check on your end once the CI produces the binary? Thank you very much for your patience

**Comment by InfiniteCod3** [comment]
Hi, the problem has been solved hopper no longer eats the whole cpu. Thanks for the quick fix 👍
